[project]
authors = ["Mark Servilla <mark.servilla@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "PinchMe"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.1,<3.14"
click = "*"
daiquiri = "*"
pendulum = "*"
pytest = "*"
sqlite = "*"
psycopg2 = "*"
sqlalchemy = ">=1.4.51,<2.0"
pixi-pycharm = ">=0.0.8,<0.0.9"
pip = ">=25.1.1,<26"
